import Foundation

/// Descriptor-driven installer for OpenCode, Hermes, and AntiGravity.
/// Provider config is touched only when the tool is detected, foreign entries
/// are preserved, originals are backed up, and unchanged files are not written.
enum ProviderInstaller {

    enum Format {
        case opencodePlugin // OpenCode: JS plugin file + register in opencode.json
        case hermesYAML // Hermes: merge a hooks map into ~/.hermes/config.yaml
        case antigravityJSON // AntiGravity: named hook group in ~/.gemini/config/hooks.json
    }

    struct Descriptor {
        let source: String
        let displayName: String
        let configDirRel: String
        let configFileRel: String
        let format: Format
        let events: [(name: String, timeout: Int)]
        var detectPaths: [String] = []
    }

    // MARK: - Provider descriptors

    static let descriptors: [Descriptor] = [
        Descriptor(source: "opencode", displayName: "OpenCode",
                   configDirRel: ".config/opencode", configFileRel: "opencode.json",
                   format: .opencodePlugin, events: []),
        Descriptor(source: "antigravity", displayName: "AntiGravity",
                   configDirRel: ".gemini/config", configFileRel: "hooks.json",
                   format: .antigravityJSON, events: [], detectPaths: [".gemini/antigravity"]),
        Descriptor(source: "hermes", displayName: "Hermes",
                   configDirRel: ".hermes", configFileRel: "config.yaml",
                   format: .hermesYAML,
                   events: [("on_session_start", 5),
                            ("pre_llm_call", 5), ("post_llm_call", 5),
                            ("pre_tool_call", 300), ("post_tool_call", 5), ("subagent_stop", 5)]),
    ]

    // MARK: - Entry point

    @discardableResult
    static func installAll() -> Bool {
        var allOK = true
        for d in descriptors where shouldInstall(d) {
            if !install(d) { allOK = false }
        }
        return allOK
    }

    /// Manual reinstall for one provider (Settings → Integrations button).
    /// Installs even if the tool's dir is absent, pre-staging its config.
    @discardableResult
    static func installSource(_ source: String) -> Bool {
        guard let d = descriptors.first(where: { $0.source == source }) else { return false }
        return install(d)
    }

    private static var home: URL { FileManager.default.homeDirectoryForCurrentUser }

    private static func configDir(_ d: Descriptor) -> URL {
        home.appendingPathComponent(d.configDirRel)
    }

    /// Install only when the tool is present.
    private static func shouldInstall(_ d: Descriptor) -> Bool {
        if !d.detectPaths.isEmpty {
            return d.detectPaths.contains {
                FileManager.default.fileExists(atPath: home.appendingPathComponent($0).path)
            }
        }
        return FileManager.default.fileExists(atPath: configDir(d).path)
    }

    @discardableResult
    static func install(_ d: Descriptor) -> Bool {
        installLauncher(source: d.source)
        switch d.format {
        case .opencodePlugin: return installOpenCodePlugin(d)
        case .hermesYAML:     return installHermesYAML(d)
        case .antigravityJSON: return installAntigravityJSON(d)
        }
    }

    // MARK: - Command + launcher

    /// The bare launcher command. Providers append `--event` when required.
    private static func launcherCommand(_ source: String) -> String {
        "\(home.path)/.aegis/bin/aegis-\(source)-bridge"
    }

    /// Writes `~/.aegis/bin/aegis-<source>-bridge` — a zsh shim that
    /// finds the app's bundled bridge and `exec`s it with `--source <source>`,
    /// forwarding any extra args (e.g. `--event <name>`) via "$@".
    private static func installLauncher(source: String) {
        let binDir = home.appendingPathComponent(".aegis/bin")
        try? FileManager.default.createDirectory(at: binDir, withIntermediateDirectories: true)
        let launcher = binDir.appendingPathComponent("aegis-\(source)-bridge")
        let bundledBridge = Bundle.main.bundleURL
            .appendingPathComponent("Contents/Helpers/AegisBridge").path
        let quotedBundledBridge = "'" + bundledBridge.replacingOccurrences(of: "'", with: "'\\''") + "'"
        let script = [
            "#!/bin/zsh",
            "# aegis-\(source)-bridge launcher (auto-generated by Aegis)",
            "H=/Contents/Helpers/AegisBridge",
            "B=\(quotedBundledBridge); [ -x \"$B\" ] && exec \"$B\" --source \(source) \"$@\"",
            "for P in \"/Applications/Aegis.app\" \"$HOME/Applications/Aegis.app\"; do",
            "  B=\"${P}${H}\"; [ -x \"$B\" ] && exec \"$B\" --source \(source) \"$@\"",
            "done",
            "D=\"$HOME/Documents/DEV/DESKTOP/AEGIS/.build/release/AegisBridge\"",
            "[ -x \"$D\" ] && exec \"$D\" --source \(source) \"$@\"",
            "D=\"$HOME/Documents/DEV/DESKTOP/AEGIS/.build/debug/AegisBridge\"",
            "[ -x \"$D\" ] && exec \"$D\" --source \(source) \"$@\"",
            "echo \"aegis-\(source)-bridge: app not found.\" >&2",
            "exit 127",
        ].joined(separator: "\n")
        try? script.write(to: launcher, atomically: true, encoding: .utf8)
        try? FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: launcher.path)
    }

    /// Read-modify-write a JSON object file: parse existing (bail if present but
    /// unparseable), apply `mutate`, back up + write only if changed.
    private static func mergeJSONObject(at url: URL, _ mutate: (inout [String: Any]) -> Void) -> Bool {
        var root: [String: Any] = [:]
        let existing = try? Data(contentsOf: url)
        if let data = existing, !data.isEmpty {
            guard let parsed = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any] else {
                Log.error("ProviderInstaller: \(url.path) exists but isn't valid JSON. Refusing to overwrite.")
                return false
            }
            root = parsed
        }
        mutate(&root)

        guard let newData = try? JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted]) else {
            Log.error("ProviderInstaller: failed to serialize \(url.path)")
            return false
        }
        if let existing, normalized(existing) == normalized(newData) { return true }
        if let existing, !existing.isEmpty {
            try? existing.write(to: url.appendingPathExtension("bak"), options: .atomic)
        }
        do {
            try newData.write(to: url, options: .atomic)
            return true
        } catch {
            Log.error("ProviderInstaller: failed to write \(url.path): \(error)")
            return false
        }
    }

    private static func normalized(_ data: Data) -> Data? {
        guard let obj = try? JSONSerialization.jsonObject(with: data) else { return nil }
        return try? JSONSerialization.data(withJSONObject: obj, options: [.sortedKeys])
    }

    // MARK: - OpenCode (JS plugin + config registration)

    /// Writes the plugin JS and adds a `file://` ref to opencode.json's
    /// `plugin` array (preferring an existing .jsonc). Skips silently if the
    /// config exists but can't be parsed (won't corrupt a hand-edited file).
    private static func installOpenCodePlugin(_ d: Descriptor) -> Bool {
        let ocDir = configDir(d)                              // ~/.config/opencode
        let pluginsDir = ocDir.appendingPathComponent("plugins")
        do {
            try FileManager.default.createDirectory(at: pluginsDir, withIntermediateDirectories: true)
        } catch {
            Log.error("ProviderInstaller(opencode): can't create \(pluginsDir.path): \(error)")
            return false
        }
        let pluginURL = pluginsDir.appendingPathComponent("aegis.js")
        // The plugin computes the bridge path at runtime (os.homedir); static.
        if (try? String(contentsOf: pluginURL, encoding: .utf8)) != openCodePluginJS {
            try? openCodePluginJS.write(to: pluginURL, atomically: true, encoding: .utf8)
        }

        // Register in opencode.jsonc if it exists, else opencode.json.
        let jsoncURL = ocDir.appendingPathComponent("opencode.jsonc")
        let configURL = FileManager.default.fileExists(atPath: jsoncURL.path)
            ? jsoncURL : ocDir.appendingPathComponent("opencode.json")
        let ok = registerOpenCodePlugin(at: configURL, pluginPath: pluginURL.path)
        if ok {
            let legacyPlugin = pluginsDir.appendingPathComponent("caesuraisland.js")
            try? FileManager.default.removeItem(at: legacyPlugin)
        }
        print("[Aegis] OpenCode plugin \(ok ? "installed" : "FAILED") (\(pluginURL.path))")
        return ok
    }

    private static func registerOpenCodePlugin(at url: URL, pluginPath: String) -> Bool {
        let ref = "file://\(pluginPath)"
        let existing = try? Data(contentsOf: url)
        var root: [String: Any] = [:]
        if let data = existing, !data.isEmpty {
            let text = String(data: data, encoding: .utf8) ?? ""
            let stripped = stripJSONComments(text)
            guard let parsed = (try? JSONSerialization.jsonObject(
                with: Data(stripped.utf8))) as? [String: Any] else {
                Log.error("ProviderInstaller(opencode): \(url.path) isn't valid JSON(C). Refusing to overwrite.")
                return false
            }
            root = parsed
        }
        if root["$schema"] == nil { root["$schema"] = "https://opencode.ai/config.json" }
        var plugins = (root["plugin"] as? [String] ?? []).filter {
            !$0.contains("aegis") && !$0.contains("caesuraisland") && !$0.contains("caesura-island")
        }
        plugins.append(ref)
        root["plugin"] = plugins

        guard let newData = try? JSONSerialization.data(
            withJSONObject: root, options: [.prettyPrinted]) else { return false }
        if let existing, normalized(existing) == normalized(newData) { return true }
        if let existing, !existing.isEmpty {
            try? existing.write(to: url.appendingPathExtension("bak"), options: .atomic)
        }
        do { try newData.write(to: url, options: .atomic); return true }
        catch { Log.error("ProviderInstaller(opencode): write failed: \(error)"); return false }
    }

    /// String/escape-aware removal of `//` and `/* */` comments so a JSONC
    /// config (and `https://` inside strings) parses correctly.
    private static func stripJSONComments(_ text: String) -> String {
        var out = ""
        var inString = false, escaped = false
        let chars = Array(text)
        var i = 0
        while i < chars.count {
            let c = chars[i]
            if inString {
                out.append(c)
                if escaped { escaped = false }
                else if c == "\\" { escaped = true }
                else if c == "\"" { inString = false }
                i += 1
                continue
            }
            if c == "\"" { inString = true; out.append(c); i += 1; continue }
            if c == "/" && i + 1 < chars.count && chars[i + 1] == "/" {
                while i < chars.count && chars[i] != "\n" { i += 1 }
                continue
            }
            if c == "/" && i + 1 < chars.count && chars[i + 1] == "*" {
                i += 2
                while i + 1 < chars.count && !(chars[i] == "*" && chars[i + 1] == "/") { i += 1 }
                i += 2
                continue
            }
            out.append(c); i += 1
        }
        return out
    }

    // MARK: - Hermes (Nous Research — config.yaml `hooks:` map)

    private static let hermesMarker = "# aegis-managed"

    /// Merges managed commands into the top-level `hooks:` map while preserving
    /// every foreign event and command. Hermes may re-serialize the YAML and
    /// remove comments, so command identity is the idempotency key. Hermes still
    /// requires consent through `hermes hooks` unless auto-accept is configured.
    private static func installHermesYAML(_ d: Descriptor) -> Bool {
        installHermesYAML(
            d,
            hermesRoot: configDir(d),
            launcherCommand: launcherCommand(d.source)
        )
    }

    static func installHermesYAML(
        _ d: Descriptor,
        hermesRoot: URL,
        launcherCommand cmd: String
    ) -> Bool {
        let fileManager = FileManager.default
        let rootConfig = hermesRoot.appendingPathComponent(d.configFileRel)
        let profilesRoot = hermesRoot.appendingPathComponent("profiles", isDirectory: true)
        let profileDirectories = (try? fileManager.contentsOfDirectory(
            at: profilesRoot,
            includingPropertiesForKeys: [.isDirectoryKey],
            options: [.skipsHiddenFiles]
        )) ?? []
        let profileConfigs = profileDirectories
            .filter { (try? $0.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true }
            .map { $0.appendingPathComponent(d.configFileRel) }
            .filter { fileManager.fileExists(atPath: $0.path) }
            .sorted { $0.path < $1.path }
        let configURLs = (fileManager.fileExists(atPath: rootConfig.path) ? [rootConfig] : []) + profileConfigs
        guard !configURLs.isEmpty else {
            Log.info("ProviderInstaller(hermes): no config.yaml — skipping (Hermes not set up)")
            return true
        }

        var allSucceeded = true
        for fileURL in configURLs where !mergeHermesHooks(d, into: fileURL, command: cmd) {
            allSucceeded = false
        }
        return allSucceeded
    }

    private static func mergeHermesHooks(_ d: Descriptor, into fileURL: URL, command cmd: String) -> Bool {
        guard let existing = try? String(contentsOf: fileURL, encoding: .utf8) else {
            Log.error("ProviderInstaller(hermes): failed to read \(fileURL.path)")
            return false
        }
        var lines = removingLegacyHermesHooks(from: existing.components(separatedBy: "\n"))
        let escapedCommand = cmd.replacingOccurrences(of: "'", with: "''")
        let start: Int
        if let existingStart = lines.firstIndex(where: {
            let trimmed = $0.trimmingCharacters(in: .whitespaces)
            return $0 == trimmed && (trimmed == "hooks:" || trimmed == "hooks: {}")
        }) {
            start = existingStart
            if lines[start].trimmingCharacters(in: .whitespaces) == "hooks: {}" {
                lines[start] = "hooks:"
            }
        } else {
            if !(lines.last?.isEmpty ?? true) { lines.append("") }
            start = lines.count
            lines.append("hooks:")
        }

        var end = start + 1
        while end < lines.count, lines[end].hasPrefix(" ") || lines[end].hasPrefix("\t") { end += 1 }

        if !lines[start..<end].contains(where: { $0.contains(hermesMarker) }) {
            lines.insert("  \(hermesMarker)", at: start + 1)
            end += 1
        }

        for (event, seconds) in d.events {
            let header = "  \(event):"
            if let eventStart = lines[start..<end].firstIndex(of: header) {
                var eventEnd = eventStart + 1
                while eventEnd < end {
                    let line = lines[eventEnd]
                    if line.hasPrefix("  "), !line.hasPrefix("   "),
                       line.trimmingCharacters(in: .whitespaces).hasSuffix(":") {
                        break
                    }
                    eventEnd += 1
                }
                let alreadyInstalled = lines[eventStart..<eventEnd].contains { $0.contains(cmd) }
                if !alreadyInstalled {
                    lines.insert(contentsOf: [
                        "    - command: '\(escapedCommand)'",
                        "      timeout: \(seconds)",
                    ], at: eventEnd)
                    end += 2
                }
            } else {
                lines.insert(contentsOf: [
                    header,
                    "    - command: '\(escapedCommand)'",
                    "      timeout: \(seconds)",
                ], at: end)
                end += 3
            }
        }

        let newText = lines.joined(separator: "\n")
        if newText == existing { return true }
        try? existing.write(to: fileURL.appendingPathExtension("bak"), atomically: true, encoding: .utf8)
        do { try newText.write(to: fileURL, atomically: true, encoding: .utf8)
             print("[Aegis] Hermes hooks written to \(fileURL.path) (approve via `hermes hooks`)"); return true }
        catch { Log.error("ProviderInstaller(hermes): write failed: \(error)"); return false }
    }

    private static func removingLegacyHermesHooks(from lines: [String]) -> [String] {
        var cleaned: [String] = []
        var skipTimeout = false

        for line in lines {
            let isLegacyMarker = line.trimmingCharacters(in: .whitespaces) == "# caesura-island-managed"
            let isLegacyCommand = line.contains("/.caesura-island/bin/caesura-island-hermes-bridge")
            if isLegacyMarker || isLegacyCommand {
                skipTimeout = isLegacyCommand
                continue
            }
            if skipTimeout, line.trimmingCharacters(in: .whitespaces).hasPrefix("timeout:") {
                skipTimeout = false
                continue
            }
            skipTimeout = false
            cleaned.append(line)
        }

        return cleaned
    }

    // MARK: - AntiGravity (Google — ~/.gemini/config/hooks.json named group)

    /// Writes a "aegis" hook group into ~/.gemini/config/hooks.json.
    /// Tool events use `{matcher, hooks:[…]}`; invocation/stop events use bare
    /// `{type,command}`. Event name is passed via `--event` (the payload has no
    /// event-name field). NOTE: Antigravity caches hooks at daemon startup, so
    /// a running session must be restarted to pick these up.
    private static func installAntigravityJSON(_ d: Descriptor) -> Bool {
        let fileURL = configDir(d).appendingPathComponent(d.configFileRel)   // ~/.gemini/config/hooks.json
        try? FileManager.default.createDirectory(
            at: fileURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        let cmd = launcherCommand(d.source)
        func handler(_ event: String) -> [String: Any] {
            ["type": "command", "command": "\(cmd) --event \(event)", "timeout": 10]
        }
        let ok = mergeJSONObject(at: fileURL) { root in
            root.removeValue(forKey: "caesura-island")
            root["aegis"] = [
                "enabled": true,
                "PreInvocation": [handler("PreInvocation")],
                "Stop": [handler("Stop")],
                "PreToolUse":  [["matcher": "*", "hooks": [handler("PreToolUse")]]],
                "PostToolUse": [["matcher": "*", "hooks": [handler("PostToolUse")]]],
            ]
        }
        print("[Aegis] AntiGravity hooks \(ok ? "installed" : "FAILED") in \(fileURL.path) (restart AntiGravity to load)")
        return ok
    }

    // MARK: - OpenCode plugin source

    /// The OpenCode plugin: maps OpenCode's event vocabulary → our canonical
    /// events and shells out to aegis-opencode-bridge (JSON on stdin,
    /// `--event <name>`). Blocking events (permission/question) read the
    /// bridge's stdout decision and reply via OpenCode's HTTP API.
    private static let openCodePluginJS = #"""
// aegis-opencode plugin — auto-generated by Aegis. Do not edit.
import { execFile } from "child_process";
import { homedir } from "os";
import { join } from "path";

const BRIDGE = join(homedir(), ".aegis", "bin", "aegis-opencode-bridge");

function send(canonicalEvent, payload) {
  try {
    const child = execFile(BRIDGE, ["--source", "opencode", "--event", canonicalEvent],
      { timeout: 8000, maxBuffer: 1024 * 1024 }, () => {});
    child.stdin.write(JSON.stringify(payload));
    child.stdin.end();
  } catch {}
}

function sendAndWait(canonicalEvent, payload, timeoutMs = 300000) {
  return new Promise((resolve) => {
    try {
      const child = execFile(BRIDGE, ["--source", "opencode", "--event", canonicalEvent],
        { timeout: timeoutMs, maxBuffer: 1024 * 1024 }, (error, stdout) => {
          if (error) { resolve(null); return; }
          try { resolve(JSON.parse(stdout)); } catch { resolve(null); }
        });
      child.stdin.write(JSON.stringify(payload));
      child.stdin.end();
    } catch { resolve(null); }
  });
}

export default {
  id: "aegis",
  server: async ({ client, serverUrl }) => {
    const serverPort = serverUrl ? (parseInt(serverUrl.port) || 4096) : 4096;
    const heyApi = client?._client;

    const sessionCwd = new Map();
    const msgRoles = new Map();
    const lastAssistant = new Map();

    function base(sid, extra) {
      return { session_id: `opencode-${sid}`, _source: "opencode", ...extra };
    }

    async function replyPermission(sessionId, permissionId, response) {
      // OpenCode API: POST /session/{id}/permissions/{permissionID} with
      // body { response: "once" | "always" | "reject" }.
      try {
        if (typeof heyApi?.request === "function") {
          await heyApi.request({ method: "POST", url: "/session/{id}/permissions/{permissionID}",
            path: { id: sessionId, permissionID: permissionId }, body: { response } });
          return;
        }
      } catch {}
      try {
        await fetch(`http://localhost:${serverPort}/session/${sessionId}/permissions/${permissionId}`, {
          method: "POST", headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ response }) });
      } catch {}
    }

    async function replyQuestion(requestId, answers) {
      try {
        if (typeof heyApi?.request === "function") {
          await heyApi.request({ method: "POST", url: "/question/{requestID}/reply",
            path: { requestID: requestId }, body: { answers } });
          return;
        }
      } catch {}
      try {
        await fetch(`http://localhost:${serverPort}/question/${requestId}/reply`, {
          method: "POST", headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ answers }) });
      } catch {}
    }

    async function rejectQuestion(requestId) {
      try {
        if (typeof heyApi?.request === "function") {
          await heyApi.request({ method: "POST", url: "/question/{requestID}/reject",
            path: { requestID: requestId } });
          return;
        }
      } catch {}
      try {
        await fetch(`http://localhost:${serverPort}/question/${requestId}/reject`, {
          method: "POST", headers: { "Content-Type": "application/json" } });
      } catch {}
    }

    return {
      "event": async ({ event }) => {
        const t = event.type;
        const p = event.properties || {};

        if (t === "session.created" && p.info) {
          sessionCwd.set(p.info.id, p.info.directory || "");
          send("SessionStart", base(p.info.id, { hook_event_name: "SessionStart", cwd: p.info.directory || "" }));
          return;
        }
        if (t === "session.deleted" && p.info) {
          sessionCwd.delete(p.info.id); lastAssistant.delete(p.info.id);
          send("SessionEnd", base(p.info.id, { hook_event_name: "SessionEnd" }));
          return;
        }
        if (t === "session.updated" && p.info?.time?.archived) {
          sessionCwd.delete(p.info.id); lastAssistant.delete(p.info.id);
          send("SessionEnd", base(p.info.id, { hook_event_name: "SessionEnd" }));
          return;
        }

        if (t === "session.status" && p.sessionID && p.status?.type === "idle") {
          send("Stop", base(p.sessionID, { hook_event_name: "Stop",
            cwd: sessionCwd.get(p.sessionID),
            last_assistant_message: lastAssistant.get(p.sessionID) || undefined }));
          return;
        }

        if (t === "message.updated" && p.info?.id && p.info?.sessionID) {
          msgRoles.set(p.info.id, { role: p.info.role, sessionID: p.info.sessionID });
          if (msgRoles.size > 200) msgRoles.delete(msgRoles.keys().next().value);
          return;
        }
        if (t === "message.part.updated" && p.part?.type === "text" && p.part?.messageID) {
          const meta = msgRoles.get(p.part.messageID);
          if (!meta) return;
          const text = p.part.text || "";
          if (meta.role === "user" && text) {
            send("UserPromptSubmit", base(meta.sessionID, { hook_event_name: "UserPromptSubmit",
              cwd: sessionCwd.get(meta.sessionID), prompt: text }));
          } else if (meta.role === "assistant" && text) {
            lastAssistant.set(meta.sessionID, text);
          }
          return;
        }

        if (t === "message.part.updated" && p.part?.type === "tool" && p.part?.sessionID) {
          const st = p.part.state?.status;
          const tool = (p.part.tool || "");
          const toolName = tool.charAt(0).toUpperCase() + tool.slice(1);
          const cwd = sessionCwd.get(p.part.sessionID);
          if (st === "running" || st === "pending") {
            send("PreToolUse", base(p.part.sessionID, { hook_event_name: "PreToolUse",
              cwd, tool_name: toolName, tool_input: p.part.state?.input || {} }));
          } else if (st === "completed" || st === "error") {
            send("PostToolUse", base(p.part.sessionID, { hook_event_name: "PostToolUse",
              cwd, tool_name: toolName }));
          }
          return;
        }

        if (t === "permission.asked" && p.id && p.sessionID) {
          const perm = p.permission || "";
          const toolName = perm.charAt(0).toUpperCase() + perm.slice(1);
          const patterns = p.patterns || [];
          const toolInput = { patterns, metadata: p.metadata };
          if (perm === "bash" && patterns.length) toolInput.command = patterns.join(" && ");
          if ((perm === "edit" || perm === "write") && patterns.length) toolInput.file_path = patterns[0];
          const payload = base(p.sessionID, { hook_event_name: "PermissionRequest",
            cwd: sessionCwd.get(p.sessionID), tool_name: toolName, tool_input: toolInput });
          const resp = await sendAndWait("PermissionRequest", payload);
          const decision = resp?.hookSpecificOutput?.decision;
          const behavior = decision?.behavior;
          if (!behavior) return;
          const hasUpdated = decision?.updatedPermissions != null;
          const reply = (behavior === "always" || (behavior === "allow" && hasUpdated)) ? "always"
            : behavior === "allow" ? "once" : "reject";
          await replyPermission(p.sessionID, p.id, reply);
          return;
        }
        if (t === "permission.replied" && p.sessionID) {
          send("PostToolUse", base(p.sessionID, { hook_event_name: "PostToolUse",
            cwd: sessionCwd.get(p.sessionID) }));
          return;
        }

        if (t === "question.asked" && p.id && p.sessionID) {
          const questions = (p.questions || []).map((q) => ({
            question: q.question || "", header: q.header || "",
            options: (q.options || []).map((o) => ({ label: o.label, description: o.description })),
            multiSelect: q.multiple || false }));
          const payload = base(p.sessionID, { hook_event_name: "PermissionRequest",
            cwd: sessionCwd.get(p.sessionID), tool_name: "AskUserQuestion",
            tool_input: { questions } });
          const resp = await sendAndWait("PermissionRequest", payload);
          const decision = resp?.hookSpecificOutput?.decision;
          if (!decision) return;
          if (decision.behavior === "deny") { await rejectQuestion(p.id); return; }
          const answers = decision?.updatedInput?.answers;
          if (!answers) return;
          await replyQuestion(p.id, Object.values(answers).map((v) => [v]));
          return;
        }
        if ((t === "question.replied" || t === "question.rejected") && p.sessionID) {
          send("PostToolUse", base(p.sessionID, { hook_event_name: "PostToolUse",
            cwd: sessionCwd.get(p.sessionID) }));
          return;
        }
      },
    };
  },
};
"""#
}
